#' Exhibit  mapping
#'
#' @export
gisa_exhibit_mapping <- function() {
  tibble::tribble(
    ~file, ~section_number, ~exhibit, ~format_number,
    "LIAB2001", "1", "Analysis by Large Incurred Losses by Coverage/Policy Form within Major Class", "3",
    "LIAB2001", "2", "Analysis by Large Incurred Losses by Coverage/Policy Form for all Major Classes", "3",
    "LIAB2101", "1", "Analysis by Large Incurred Losses by Industry Code", "4",
    "LIAB4501", "1", "Loss Development - CGL - with product/completed operations", "10",
    "LIAB4501", "2", "CGL - with product/completed operations - Total of all KoLs", "10",
    "LIAB4501", "3", "CGL - without product/completed operations", "10",
    "LIAB4501", "4", "CGL - without product/completed operations - Total of all KoLs", "10",
    "LIAB4501", "5", "Tenants' Legal Liability", "10",
    "LIAB4501", "6", "Tenants' Legal Liability - Total of all KoLs", "10",
    "LIAB4501", "7", "Excess Liability", "10",
    "LIAB4501", "8", "Excess Liability - Total of all KoLs", "10",
    "LIAB4501", "9", "Umbrella Liability", "10",
    "LIAB4501", "10", "Umbrella Liability - Total of all KoLs", "10",
    "LIAB4501", "11", "Auto Liability - Excess Liability", "10",
    "LIAB4501", "12", "Auto Liability - Excess Liability - Total of all KoLs", "10",
    "LIAB4501", "13", "Auto Liability - Non-owned Automobile", "10",
    "LIAB4501", "14", "Auto Liability - Non-owned Automobile - Total of all KoLs", "10",
    "LIAB4501", "15", "Auto Liability - Contingent Lessors Liability", "10",
    "LIAB4501", "16", "Auto Liability - Contingent Lessors Liability - Total of all KoLs", "10",
    "LIAB4501", "17", "Wrap-up Liability", "10",
    "LIAB4501", "18", "Wrap-up Liability - Total of all KoLs", "10",
    "LIAB4501", "19", "Professional Liability - Occurrence basis", "10",
    "LIAB4501", "20", "Professional Liability - Occurrence basis - Total of all KoLs", "10",
    "LIAB4501", "21", "Professional Liability - Claims-made basis", "10",
    "LIAB4501", "22", "Professional Liability - Claims-made basis - Total of all KoLs", "10",
    "LIAB4501", "23", "Professional Liability - All Policies", "10",
    "LIAB4501", "24", "Professional Liability - All Policies - Total of all KoLs", "10",
    "LIAB4501", "25", "Professional Liability (other than Directors' & Officers' Liability) - Occurrence basis", "10",
    "LIAB4501", "26", "Professional Liability (other than Directors' & Officers' Liability) - Occurrence basis - Total of all KoLs", "10",
    "LIAB4501", "27", "Professional Liability (other than Directors' & Officers' Liability) - Claims-made basis", "10",
    "LIAB4501", "28", "Professional Liability (other than Directors' & Officers' Liability) - Claims-made basis - Total of all KoLs", "10",
    "LIAB4501", "29", "Professional Liability (other than Directors' & Officers' Liability) - All Policies", "10",
    "LIAB4501", "30", "Professional Liability (other than Directors' & Officers' Liability) - All Policies - Total of all KoLs", "10",
    "LIAB4501", "31", "Directors' & Officers' Liability - Occurrence basis", "10",
    "LIAB4501", "32", "Directors' & Officers' Liability - Occurrence basis - Total of all KoLs", "10",
    "LIAB4501", "33", "Directors' & Officers' Liability - Claims-made basis", "10",
    "LIAB4501", "34", "Directors' & Officers' Liability - Claims-made basis - Total of all KoLs", "10",
    "LIAB4501", "35", "Directors' & Officers' Liability - All Policies", "10",
    "LIAB4501", "36", "Directors' & Officers' Liability - All Policies - Total of all KoLs", "10",
    "LIAB4501", "37", "Pollution Liability - Written as a separate policy (e.g. Environmental Impairment Liability)", "10",
    "LIAB4501", "38", "Pollution Liability - Written as a separate policy (e.g. Environmental Impairment Liability) - Total of all KoLs", "10",
    "LIAB4501", "39", "Pollution Liability - Buy-back, Employers' Liability (including Voluntary compensation)", "10",
    "LIAB4501", "40", "Pollution Liability - Buy-back, Employers' Liability (including Voluntary compensation) - Total of all KoLs", "10",
    "LIAB4501", "41", "Employers' Liability (including Voluntary compensation)", "10",
    "LIAB4501", "42", "Employers' Liability (including Voluntary compensation) - Total of all KoLs", "10",
    "LIAB4501", "43", "Total of All Coverages/Policy Form", "10",
    "LIAB4501", "44", "Total of All Coverages/Policy Form - Total of all KoLs", "10"
  )
}
