#' Exhibit  mapping
#'
gisa_exhibit_mapping <- function() {
  tibble::tribble(
    ~file, ~section_number, ~exhibit, ~format_number,
    "LIAB2001", "1", "Analysis by Large Incurred Losses by Coverage/Policy Form within Major Class", "3",
    "LIAB2001", "2", "Analysis by Large Incurred Losses by Coverage/Policy Form for all Major Classes", "3",
    "LIAB2101", "1", "Analysis by Large Incurred Losses by Industry Code", "4",
    "LIAB4501", "1", "Loss Development - CGL - with product/completed operations", "10",
    "LIAB4501", "2", "Loss Development - CGL - with product/completed operations - Total of all KoLs", "10",
    "LIAB4501", "3", "Loss Development - CGL - without product/completed operations", "10",
    "LIAB4501", "4", "Loss Development - CGL - without product/completed operations - Total of all KoLs", "10",
    "LIAB4501", "5", "Loss Development - Tenants' Legal Liability", "10",
    "LIAB4501", "6", "Loss Development - Tenants' Legal Liability - Total of all KoLs", "10",
    "LIAB4501", "7", "Loss Development - Excess Liability", "10",
    "LIAB4501", "8", "Loss Development - Excess Liability - Total of all KoLs", "10",
    "LIAB4501", "9", "Loss Development - Umbrella Liability", "10",
    "LIAB4501", "10", "Loss Development - Umbrella Liability - Total of all KoLs", "10",
    "LIAB4501", "11", "Loss Development - Auto Liability - Excess Liability", "10",
    "LIAB4501", "12", "Loss Development - Auto Liability - Excess Liability - Total of all KoLs", "10",
    "LIAB4501", "13", "Loss Development - Auto Liability - Non-owned Automobile", "10",
    "LIAB4501", "14", "Loss Development - Auto Liability - Non-owned Automobile - Total of all KoLs", "10",
    "LIAB4501", "15", "Loss Development - Auto Liability - Contingent Lessors Liability", "10",
    "LIAB4501", "16", "Loss Development - Auto Liability - Contingent Lessors Liability - Total of all KoLs", "10",
    "LIAB4501", "17", "Loss Development - Wrap-up Liability", "10",
    "LIAB4501", "18", "Loss Development - Wrap-up Liability - Total of all KoLs", "10",
    "LIAB4501", "19", "Loss Development - Professional Liability - Occurrence basis", "10",
    "LIAB4501", "20", "Loss Development - Professional Liability - Occurrence basis - Total of all KoLs", "10",
    "LIAB4501", "21", "Loss Development - Professional Liability - Claims-made basis", "10",
    "LIAB4501", "22", "Loss Development - Professional Liability - Claims-made basis - Total of all KoLs", "10",
    "LIAB4501", "23", "Loss Development - Professional Liability - All Policies", "10",
    "LIAB4501", "24", "Loss Development - Professional Liability - All Policies - Total of all KoLs", "10",
    "LIAB4501", "25", "Loss Development - Professional Liability (other than Directors' & Officers' Liability) - Occurrence basis", "10",
    "LIAB4501", "26", "Loss Development - Professional Liability (other than Directors' & Officers' Liability) - Occurrence basis - Total of all KoLs", "10",
    "LIAB4501", "27", "Loss Development - Professional Liability (other than Directors' & Officers' Liability) - Claims-made basis", "10",
    "LIAB4501", "28", "Loss Development - Professional Liability (other than Directors' & Officers' Liability) - Claims-made basis - Total of all KoLs", "10",
    "LIAB4501", "29", "Loss Development - Professional Liability (other than Directors' & Officers' Liability) - All Policies", "10",
    "LIAB4501", "30", "Loss Development - Professional Liability (other than Directors' & Officers' Liability) - All Policies - Total of all KoLs", "10",
    "LIAB4501", "31", "Loss Development - Directors' & Officers' Liability - Occurrence basis", "10",
    "LIAB4501", "32", "Loss Development - Directors' & Officers' Liability - Occurrence basis - Total of all KoLs", "10",
    "LIAB4501", "33", "Loss Development - Directors' & Officers' Liability - Claims-made basis", "10",
    "LIAB4501", "34", "Loss Development - Directors' & Officers' Liability - Claims-made basis - Total of all KoLs", "10",
    "LIAB4501", "35", "Loss Development - Directors' & Officers' Liability - All Policies", "10",
    "LIAB4501", "36", "Loss Development - Directors' & Officers' Liability - All Policies - Total of all KoLs", "10",
    "LIAB4501", "37", "Loss Development - Pollution Liability - Written as a separate policy (e.g. Environmental Impairment Liability)", "10",
    "LIAB4501", "38", "Loss Development - Pollution Liability - Written as a separate policy (e.g. Environmental Impairment Liability) - Total of all KoLs", "10",
    "LIAB4501", "39", "Loss Development - Pollution Liability - Buy-back, Employers' Liability (including Voluntary compensation)", "10",
    "LIAB4501", "40", "Loss Development - Pollution Liability - Buy-back, Employers' Liability (including Voluntary compensation) - Total of all KoLs", "10",
    "LIAB4501", "41", "Loss Development - Employers' Liability (including Voluntary compensation)", "10",
    "LIAB4501", "42", "Loss Development - Employers' Liability (including Voluntary compensation) - Total of all KoLs", "10",
    "LIAB4501", "43", "Loss Development - Total of All Coverages/Policy Form", "10",
    "LIAB4501", "44", "Loss Development - Total of All Coverages/Policy Form - Total of all KoLs", "10",
    "AUTO6001", "4", "Catastrophe Report - All classes Comprehensive, All Perils and Specified Perils", "21", # (NB, NL, NS, and PE)
    "AUTO6001", "8", "Catastrophe Report - All classes Comprehensive, All Perils and Specified Perils", "21", # (NL)
    "AUTO6001", "12", "Catastrophe Report - All classes Comprehensive, All Perils and Specified Perils", "21", # (NS)
    "AUTO6001", "16", "Catastrophe Report - All classes Comprehensive, All Perils and Specified Perils", "21", # (PE)
    "AUTO7001", "1", "Loss development exhibit - Private Passenger - Exposures and Premium distribution", "5",
    "AUTO7001", "2", "Loss development exhibit - Private Passenger - Third Party Liability", "6",
    "AUTO7001", "3", "Loss development exhibit - Private Passenger - Accident Benefits", "6",
    "AUTO7001", "4", "Loss development exhibit - Private Passenger - Underinsured Motorist", "6",
    "AUTO7001", "5", "Loss development exhibit - Private Passenger - All Perils", "6",
    "AUTO7001", "6", "Loss development exhibit - Private Passenger - Collision", "6",
    "AUTO7001", "7", "Loss development exhibit - Private Passenger - Comprehensive", "6",
    "AUTO7001", "8", "Loss development exhibit - Private Passenger - Specified Perils", "6",
    "AUTO7001", "9", "Loss development exhibit - Private Passenger - Uninsured Automobile", "6"
  )
}
